#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'

Dir.chdir(File.realpath(File.dirname(__FILE__) + '/../'))

command_name = ARGV.shift

case command_name
when 'start'
  exec "bundle exec puma #{ARGV.join(' ')}"
when 'reload'
  Process.kill(
    'USR1', File.read(ENV.fetch('PUMA_PID_FILE', 'tmp/puma.pid')).to_i
  )
when 'restart'
  Process.kill(
    'USR2', File.read(ENV.fetch('PUMA_PID_FILE', 'tmp/puma.pid')).to_i
  )
when 'stop'
  Process.kill(
    'TERM', File.read(ENV.fetch('PUMA_PID_FILE', 'tmp/puma.pid')).to_i
  )
when 'deploy'
  Aws::CloudFormation::
else
  abort "Unknown command: #{command_name}"
end
